version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  
  seed:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    command: python cli.py seed usuarios servicos solicitacoes planos